### PR TITLE
Add getTouches() in Visualizer extension for getting touch locations.

### PR DESCRIPTION
**Pull request by lm2343635**
Hi, morizotter!
I am using your framework TouchVisualizer in my app. But I found that I cannot get the touch locations from your framework. So I add a method called getTouches() in your extension to get touch locations.
Hope you can accept this pull request, and update your CocoaPods version so that I can download it from CocoaPods directly.
Best wishes!

### CODE REVIEW

**Comment by morizotter** [comment]
Thanks! I'll check it later!

**Comment by morizotter** [comment]
Sorry for late reply! 

Can I ask you the purpose of the method? I think touches change frequently and if you try to get touches, you have to call the method during fingers on the screen.

If you can paste the code frangemts, it's better for my understanding!

Thanks!

@lm2343635

**Comment by lm2343635** [comment]
I write a app calked lucky dog(https://github.com/lm2343635/Lots/blob/master/README.md). You can download it from App Store(https://itunes.apple.com/app/lucky-dogs/id1201592794) to see this app so that you can understand my purpose easily.
I used this method in the delegate method touchesbegain(https://github.com/lm2343635/Lots/blob/master/Lots/LotsViewController.swift)
Best wishes!

**Comment by lm2343635** [comment]
Can you receive this pull request or give me some suggestions. @morizotter

**Comment by morizotter** [comment]
Sorry for late response. I didn't have room for managing my repos for a long time. Finally, I merged your pr!

I also created demo for new method: https://github.com/morizotter/TouchVisualizer/pull/75/files .

It's complicated to get touch state. But I thought the method have values for a kind of debug. Thanks!

**Pull request merged**
