### PR TITLE
Change name from TouchVisualizerConfiguration => Configuration

### PR DESCRIPTION
**Pull request by istx25**
#31

### CODE REVIEW

**Comment by istx25** [comment]
I see what you mean @morizotter. Maybe `Configuration` is better!

**Comment by istx25** [comment]
@morizotter?

**Comment by morizotter** [comment]
@istx25 Thanks! I checked your pr :+1: I'll reply in a while later.

**Comment by istx25** [comment]
Merci!

—

**Comment by morizotter** [comment]
@istx25
I released [1.2.0](https://github.com/morizotter/TouchVisualizer/releases/tag/1.2.0) including your changes. Merci beaucoup :smile:

**Pull request merged**
