### PR TITLE
Fix 13.4 warnings and migrate to Swift 5.0

### PR DESCRIPTION
**Pull request by artemnovichkov**

### CODE REVIEW

**Comment by nunogoncalves** [comment]
We need this!

**Review by mredig — APPROVED** [review]
These changes look good to me. +1 on merging!

(Note: This review is unsolicited, but these changes are exactly what I was going to do before I saw the PR)

**Comment by nunogoncalves** [comment]
Hi! 
Any news on this?

**Comment by zaggo** [comment]
+1

**Comment by dustinrwh** [comment]
@mredig thanks for all the you do for TouchVisualizer. Any way you can merge this in? Or do you know who can?

**Comment by mredig** [comment]
You're welcome, but I literally just looked at work someone else did and threw in my two cents saying that I think it looked like good work. :)

Unfortunately, I don't have the power to merge.

**Comment by dustinrwh** [comment]
Cool. I'll give my two cents as well. Just tried out the fix in my app and it works.

**Comment by dustinrwh** [comment]
@morizotter any way we can merge this in now?

**Comment by mredig** [comment]
@dustinrwh I ended up writing my own replacement for this library. Maybe it'd work for you too?

https://swiftpackageindex.com/mredig/SeaTouch

**Comment by dustinrwh** [comment]
Thanks @mredig. Looks great!

**Comment by morizotter** [comment]
Thanx for the fix!
Sorry for late merge ><

**Pull request merged**
