### PR TITLE
I've fixed the Swift syntax errors

### PR DESCRIPTION
**Pull request by osrufung**
also, some errors with non-existent categories .

### CODE REVIEW

**Comment by morizotter** [comment]
THX!

**Comment by osrufung** [comment]
Sorry! I cannot fix the Circle.yml config file. Can you do it? :)

**Comment by osrufung** [comment]
I'll send you another PR fixing the Object-C -> Swift interoperability tomorrow ;)

Thanks for your time

**Comment by morizotter** [comment]
I'll merge this pr. thx:)

Circle ci..mm. I'll try to check it.

**Pull request merged**
