### PR TITLE
make it compatible for iOS 10 and Xcode 8

### PR DESCRIPTION
**Pull request by zarghol**

### CODE REVIEW

**Comment by zarghol** [comment]
the CI failed due to the changed in UIKit between iOS 9 and iOS 10.0 in the Example Project

**Comment by morizotter** [comment]
Thanks!

**Comment by zarghol** [comment]
CI Failed due to Swift 3 syntax...
`error: expected identifier after '.' expression
        let alertAction = UIAlertAction(title: "Show Alert", style: .default, handler: { [unowned self] (alertAction) -> Void in`

`error: expected declaration
    fileprivate var enabled = false`

etc...

**Comment by morizotter** [comment]
Thanks again for your contribution!

**Pull request merged**
