### PR TITLE
Spelling correction and two bug fixes

### PR DESCRIPTION
**Pull request by sixfngers**
bug fix - stop removes all touch views from view and prevents new ones from populating
---- previously calling TouchVisualizer.stop() would not stop new touches from showing on the screen

bug fix - changing config in TouchVisualizer adjusts new and previously created TouchViews
---- previously if you set a new config (Example: you want touches to be a different colors in different views) any previously created touchViews would not update

### CODE REVIEW

**Comment by morizotter** [comment]
Thanks for pr! If you're still working, it is preferable to add `[WIP]` at the head of issue title :smile_cat:

**Comment by morizotter** [comment]
## After merge - for me
- [x] Update spec's source
- [x] pod trunk push

**Comment by morizotter** [comment]
Thanks for your contribution! :beers:

**Comment by sixfngers** [comment]
no problem. As for the [WIP] comment do you mean the title of my pull request should have been 
"[WIP] Spelling correction and two bug fixes"

**Pull request merged**
